import { afterEach, describe, expect, it, vi } from 'vitest'
const calls = vi.hoisted(() => ({ history: vi.fn(), state: vi.fn(), detail: vi.fn(), epochs: vi.fn(), conversations: vi.fn() }))
vi.mock('../../../src/renderer/api', () => ({ api: { teamChatMessages: calls.history, appChatSessionState: calls.state, teamGetDetail: calls.detail, teamListEpochs: calls.epochs, teamListConversations: calls.conversations } }))
vi.mock('../../../src/renderer/i18n', () => ({ default: { t: (s: string) => s } }))
import { loadTeamSessionHistory, retainTeamSessionHistory, matchesTeamHistory } from '../../../src/renderer/components/team/session-history'
import { observeExecution } from '../../../src/renderer/components/team/workbench/execution-state'
import { useTeamStore } from '../../../src/renderer/stores/team.store'

afterEach(() => { vi.clearAllMocks(); vi.useRealTimers() })
describe('workbench I/O budget', () => {
  it('coalesces three transcript owners and refreshes only the changed tail', async () => {
    const release = retainTeamSessionHistory('a', 's', 't', 'e')
    calls.history.mockResolvedValueOnce({ success: true, data: [{ id: '1', seq: 1 }, { id: '2', seq: 2 }, { id: '3', seq: 3 }] })
    const snapshots = await Promise.all([0, 1, 2].map(() => loadTeamSessionHistory('a', 's', 't', 'e')))
    expect(calls.history).toHaveBeenCalledTimes(1)
    expect(snapshots[0].data).toHaveLength(3)
    calls.history.mockResolvedValueOnce({ success: true, data: [{ id: '3', seq: 3, content: 'updated' }, { id: '4', seq: 4 }] })
    const result = await loadTeamSessionHistory('a', 's', 't', 'e')
    expect(calls.history).toHaveBeenLastCalledWith('a', 's', 't', 'e', 2)
    expect(result.data).toHaveLength(4)
    expect((result.data as { content?: string }[])[2].content).toBe('updated')
    release()
    calls.history.mockResolvedValueOnce({ success: true, data: [] })
    await loadTeamSessionHistory('a', 's', 't', 'e')
    expect(calls.history).toHaveBeenLastCalledWith('a', 's', 't', 'e', undefined)
  })
  it('rejects history events from other tasks or members', () => {
    expect(matchesTeamHistory({ teamId: 't', epochId: 'other', appId: 'a' }, 't', 'e', 'a')).toBe(false)
    expect(matchesTeamHistory({ teamId: 't', epochId: 'e', appId: 'b' }, 't', 'e', 'a')).toBe(false)
    expect(matchesTeamHistory({ teamId: 't', epochId: 'e', appId: 'a' }, 't', 'e', 'a')).toBe(true)
  })
  it('shares polling until the last observer leaves', async () => {
    vi.useFakeTimers()
    calls.state.mockResolvedValue({ success: true, data: { isActive: true, thoughts: [] } })
    const first = observeExecution('a', 's', vi.fn())
    const second = observeExecution('a', 's', vi.fn())
    await vi.advanceTimersByTimeAsync(0)
    expect(calls.state).toHaveBeenCalledTimes(1)
    first()
    await vi.advanceTimersByTimeAsync(3000)
    expect(calls.state).toHaveBeenCalledTimes(2)
    second()
    await vi.advanceTimersByTimeAsync(30000)
    expect(calls.state).toHaveBeenCalledTimes(2)
  })
  it('one team update causes exactly three list/detail IPCs and no transcript fetch', async () => {
    calls.detail.mockResolvedValue({ success: false })
    calls.epochs.mockResolvedValue({ success: true, data: [] })
    calls.conversations.mockResolvedValue({ success: true, data: [] })
    useTeamStore.setState({ currentTeamId: 't', detail: null })
    useTeamStore.getState().applyTeamUpdated({ teamId: 't' })
    await Promise.resolve()
    expect(calls.detail).toHaveBeenCalledTimes(1)
    expect(calls.epochs).toHaveBeenCalledTimes(1)
    expect(calls.conversations).toHaveBeenCalledTimes(1)
    expect(calls.history).not.toHaveBeenCalled()
    useTeamStore.getState().applyTeamUpdated({ teamId: 'other' })
    expect(calls.detail).toHaveBeenCalledTimes(1)
  })
})
