// ============================================================================
// Build the dsh engine into a single-file runtime.
//
// Emits resources/dsh-runtime/, which replaces the ~400-package npm tree the
// engine used to be shipped as. See runtimes/dsh/manifest.cjs for why this is
// possible and what the pieces are.
//
//   node runtimes/dsh/build.mjs [--quiet] [--optional]
//
// --optional is how the app build runs it: dsh is an experimental engine, so a
// failure here must cost only dsh. It then removes any output, which leaves a
// build without the engine (Settings shows it unavailable) rather than one
// carrying a stale or half-written runtime, and exits 0.
// ============================================================================

import { execFileSync } from 'node:child_process'
import { builtinModules, createRequire } from 'node:module'
import { cpSync, existsSync, mkdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import esbuild from 'esbuild'

const require = createRequire(import.meta.url)
const {
  SOURCE_DIR,
  RUNTIME_DIR,
  RUNTIME_ENTRY,
  PLUGIN_PACKAGES,
  HALO_PLUGINS,
  BOOT_PACKAGE,
  EXTERNAL_PACKAGES,
  PRIVATE_EXTERNALS,
  NATIVE_COMPANIONS,
} = require('./manifest.cjs')

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const SOURCE_ROOT = path.join(PROJECT_ROOT, ...SOURCE_DIR.split('/'))
const SOURCE_MODULES = path.join(SOURCE_ROOT, 'node_modules')
const OUT_DIR = path.join(PROJECT_ROOT, ...RUNTIME_DIR.split('/'))
const OUT_ENTRY = path.join(OUT_DIR, ...RUNTIME_ENTRY.split('/'))

const quiet = process.argv.includes('--quiet')
const optional = process.argv.includes('--optional')
const log = (line) => { if (!quiet) console.log(`[dsh-runtime] ${line}`) }

/**
 * Diagnostic name the engine reports itself under. Matches the bin this bundle
 * replaces (`dsh-sdk-jsonrpc-demo/lib/packaged-bin.js`) so its log lines and
 * usage text keep meaning the same thing.
 */
const AGENT_NAME = 'dsh-jsonrpc-agent'

/** Plugin package name to the id a `cordis:` specifier carries. */
function builtinId(packageName) {
  return packageName.slice(packageName.indexOf('/') + 1)
}

/**
 * Source for the bundle entry.
 *
 * Mirrors the process lifecycle of the bin it replaces — Halo's transport stops
 * the child by closing stdin and escalates to SIGTERM (`transport/connection.ts`),
 * so both must dispose the context and exit.
 *
 * Unlike that bin it loads no `.env`: the working directory is the user's
 * workspace, and Halo hands the child an explicit environment
 * (`dsh/runtime/launch-spec.ts`) that a project file must not extend.
 *
 * It also strips the harness's own identity from every request to the model
 * endpoints Halo named (DEEPSEEK_BASE_URL / DEEPSEEK_SEARCH_BASE_URL — Halo's
 * compat router): the `User-Agent` naming DeepSeek Harness, which some
 * gateways refuse, and the `x-deepseek-harness-*` tracking ids. Doing it here
 * keeps the router free of any dsh-specific rule. Other requests (web_fetch,
 * MCP) are untouched.
 *
 * `boot`'s `bareModuleBaseUrl` is deliberately omitted. Passing it installs an
 * Include subclass that routes bare plugin names through Node's internal module
 * loader, which is exactly the disk resolution this bundle exists to avoid;
 * leaving it undefined keeps the plain Include, whose `cordis:` branch reads
 * `loader.builtins` instead.
 */
function generateEntry() {
  const plugins = [
    ...PLUGIN_PACKAGES.map((name) => ({ id: builtinId(name), specifier: name })),
    ...HALO_PLUGINS.map(({ id, source }) => ({
      id,
      specifier: path.join(PROJECT_ROOT, ...source.split('/')).split(path.sep).join('/'),
    })),
  ]
  const imports = plugins.map(({ specifier }, i) => `import * as plugin${i} from '${specifier}'`).join('\n')
  const registrations = plugins.map(({ id }, i) => `  '${id}': plugin${i},`).join('\n')

  return `// Generated by runtimes/dsh/build.mjs. Do not edit.
import { existsSync } from 'node:fs'
import { boot, installFailLoud, resolveConfigPath } from '${BOOT_PACKAGE}'
${imports}

const NAME = '${AGENT_NAME}'

const PLUGINS = {
${registrations}
}

function isModelEndpoint(input) {
  const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input?.url
  if (typeof url !== 'string') return false
  return [process.env.DEEPSEEK_BASE_URL, process.env.DEEPSEEK_SEARCH_BASE_URL]
    .some((base) => typeof base === 'string' && base !== '' && url.startsWith(base))
}

const upstreamFetch = globalThis.fetch
globalThis.fetch = (input, init) => {
  if (!isModelEndpoint(input)) return upstreamFetch(input, init)
  const headers = new Headers(init?.headers)
  for (const name of [...headers.keys()]) {
    if (name === 'user-agent' || name.startsWith('x-deepseek-harness-')) headers.delete(name)
  }
  return upstreamFetch(input, { ...init, headers })
}

async function main() {
  installFailLoud(NAME)

  const fromEnv = process.env['DSH_CORDIS_CONFIG']
  const fromArgv = process.argv[2]
  const requested = fromEnv !== undefined && fromEnv !== ''
    ? fromEnv
    : fromArgv !== undefined && fromArgv !== ''
      ? fromArgv
      : undefined
  const configPath = requested === undefined ? undefined : resolveConfigPath(requested, undefined)
  if (configPath === undefined || !existsSync(configPath)) {
    process.stderr.write(\`usage: \${NAME} <path/to/cordis.yml> (or set DSH_CORDIS_CONFIG=<path>)\\n\`)
    process.exit(1)
  }

  const ctx = await boot(NAME, configPath, undefined, (ctx) => {
    Object.assign(ctx.loader.builtins, PLUGINS)
  }, undefined)

  let exiting = false
  const disposeAndExit = async (code) => {
    if (exiting) return
    exiting = true
    try {
      await ctx.fiber.dispose()
    } finally {
      process.exit(code)
    }
  }

  process.stdin.on('end', () => { disposeAndExit(0) })
  process.on('SIGTERM', () => { disposeAndExit(0) })
  process.on('SIGINT', () => { disposeAndExit(130) })
}

await main()
`
}

/**
 * Install the engine's packages into SOURCE_DIR from its lockfile when they
 * are missing or older than it. They never enter the app's node_modules.
 */
function ensureSourceInstalled() {
  const lock = path.join(SOURCE_ROOT, 'package-lock.json')
  const installedLock = path.join(SOURCE_MODULES, '.package-lock.json')
  const fresh = existsSync(installedLock)
    && existsSync(lock)
    && statSync(installedLock).mtimeMs >= statSync(lock).mtimeMs
  if (fresh) return
  log(`installing ${SOURCE_DIR} from its lockfile`)
  execFileSync('npm', ['ci', '--no-audit', '--no-fund', '--ignore-scripts'], {
    cwd: SOURCE_ROOT,
    stdio: quiet ? 'ignore' : 'inherit',
    shell: process.platform === 'win32',
  })
}

/** Every external must travel beside the bundle; none may come from the app. */
function assertExternalsArePrivate() {
  const privateNames = new Set(PRIVATE_EXTERNALS.map(({ name }) => name))
  const shared = EXTERNAL_PACKAGES.filter((name) => !privateNames.has(name))
  if (shared.length > 0) {
    throw new Error(
      `[dsh-runtime] ${shared.join(', ')} must be listed in PRIVATE_EXTERNALS ` +
      `(runtimes/dsh/manifest.cjs): the runtime never resolves the app's packages.`
    )
  }
}

/** Fail before esbuild does, naming the package rather than a generated line. */
function assertPluginsInstalled() {
  const missing = [...PLUGIN_PACKAGES, BOOT_PACKAGE].filter(
    (name) => !existsSync(path.join(SOURCE_MODULES, ...name.split('/'), 'package.json'))
  )
  if (missing.length > 0) {
    throw new Error(
      `[dsh-runtime] not installed: ${missing.join(', ')}\n` +
      `  Add them to ${SOURCE_DIR}/package.json. If a package was renamed or dropped by a dsh release, ` +
      `update PLUGIN_PACKAGES in runtimes/dsh/manifest.cjs.`
    )
  }
}

/**
 * Assert the bundle imports nothing beyond Node builtins and the declared
 * externals.
 *
 * A dsh release that adds a native dependency would otherwise produce a bundle
 * that builds cleanly and throws ERR_MODULE_NOT_FOUND on the user's machine,
 * because the new package is neither inlined nor shipped beside the bundle.
 *
 * Reads esbuild's metafile rather than scanning the output: bundled sources
 * carry `import('...')` in JSDoc types and comments, which a text scan cannot
 * tell apart from a real import.
 */
function assertOnlyDeclaredExternals(metafile) {
  const specifiers = new Set()
  for (const output of Object.values(metafile.outputs)) {
    for (const { path: spec, external } of output.imports) {
      if (external) specifiers.add(spec)
    }
  }

  // esbuild leaves Node builtins bare when the source wrote them bare, so the
  // `node:` prefix cannot be the test. `builtinModules` omits the scheme-only
  // builtins (`node:sqlite`, `node:test`), so a prefixed name is a builtin by
  // construction.
  const builtins = new Set(builtinModules)
  const unexpected = [...specifiers].filter((spec) => {
    if (spec.startsWith('node:') || builtins.has(spec)) return false
    return !EXTERNAL_PACKAGES.some((pkg) => spec === pkg || spec.startsWith(`${pkg}/`))
  })

  if (unexpected.length > 0) {
    throw new Error(
      `[dsh-runtime] bundle imports undeclared module(s): ${unexpected.join(', ')}\n` +
      `  Either they are pure JS and should be inlined (drop them from EXTERNAL_PACKAGES),\n` +
      `  or they carry a binary and must be added to EXTERNAL_PACKAGES in ` +
      `runtimes/dsh/manifest.cjs so packaging ships them.`
    )
  }
}

/**
 * Assert every package dsh loads through its lazy-require helper is declared.
 *
 * `createLazyRequire("<name>", import.meta.url)` defers a `require` to first
 * use, so esbuild neither inlines the package nor lists it as an import: the
 * metafile check above cannot see it, and a missing one throws only when the
 * model first reaches the tool behind it.
 */
function assertLazyRequiresDeclared(code) {
  const lazy = new Set([...code.matchAll(/\bcreateLazyRequire\(\s*["']([^"']+)["']/g)].map((m) => m[1]))
  const undeclared = [...lazy].filter(
    (spec) => !EXTERNAL_PACKAGES.some((pkg) => spec === pkg || spec.startsWith(`${pkg}/`))
  )
  if (undeclared.length > 0) {
    throw new Error(
      `[dsh-runtime] bundle lazily requires undeclared package(s): ${undeclared.join(', ')}\n` +
      `  Add them to EXTERNAL_PACKAGES (and PRIVATE_EXTERNALS when dsh pins a version the app does not) ` +
      `in runtimes/dsh/manifest.cjs.`
    )
  }
}

/**
 * Manifest sitting one level above the bundle.
 *
 * Its `version` is what the dsh packages that read `../package.json` report as
 * the harness version in their outbound User-Agent, so it tracks the engine's
 * version rather than Halo's.
 */
function writeManifest() {
  const engineVersion = JSON.parse(
    readFileSync(path.join(SOURCE_MODULES, ...BOOT_PACKAGE.split('/'), 'package.json'), 'utf-8')
  ).version

  writeFileSync(
    path.join(OUT_DIR, 'package.json'),
    JSON.stringify({ name: 'dsh-runtime', version: engineVersion, private: true, type: 'module' }, null, 2) + '\n',
    'utf-8'
  )
  return engineVersion
}

/**
 * Directory of `name` as Node's lookup finds it from `fromDir`: the nearest
 * `node_modules/<name>` walking up. Walked by hand rather than through
 * `require.resolve`, which refuses `<name>/package.json` when a package's
 * `exports` does not list it (sharp 0.35).
 */
function resolvePackageDir(name, fromDir) {
  for (let dir = fromDir; ; dir = path.dirname(dir)) {
    const candidate = path.join(dir, 'node_modules', ...name.split('/'))
    if (existsSync(path.join(candidate, 'package.json'))) return candidate
    if (path.dirname(dir) === dir) throw new Error(`[dsh-runtime] cannot resolve ${name} from ${fromDir}`)
  }
}

/**
 * Plant the private externals beside the bundle, each with its production
 * dependency closure, flattened into one `node_modules`.
 *
 * A package's nested `node_modules` is not copied: its dependencies are placed
 * flat instead, and native companions are planted separately for every target.
 * Two externals needing different versions of one dependency cannot share the
 * flat tree, so that fails the build rather than picking one.
 */
function installPrivateExternals() {
  const planted = new Map()
  const plant = (name, fromDir, owner) => {
    const source = resolvePackageDir(name, fromDir)
    const manifest = JSON.parse(readFileSync(path.join(source, 'package.json'), 'utf-8'))
    const existing = planted.get(name)
    if (existing !== undefined) {
      if (existing !== manifest.version) {
        throw new Error(
          `[dsh-runtime] ${owner} needs ${name}@${manifest.version} but ${name}@${existing} is already planted`
        )
      }
      return
    }
    planted.set(name, manifest.version)
    const dest = path.join(OUT_DIR, 'node_modules', ...name.split('/'))
    mkdirSync(path.dirname(dest), { recursive: true })
    cpSync(source, dest, {
      recursive: true,
      dereference: true,
      filter: (src) => path.relative(source, src).split(path.sep)[0] !== 'node_modules',
    })
    for (const dependency of Object.keys(manifest.dependencies ?? {})) plant(dependency, source, name)
  }

  for (const { name, from } of PRIVATE_EXTERNALS) {
    plant(name, path.join(SOURCE_MODULES, ...from.split('/')), from)
    log(`${name}@${planted.get(name)}: private copy planted (for ${from})`)
  }
  log(`private externals planted: ${planted.size} package(s) with dependencies`)
}

/**
 * Plant every platform variant of the native companions beside the bundle, at
 * the version their loader pins.
 *
 * The host's variant is copied from node_modules when it matches; the others
 * are fetched from the registry once and cached, because npm refuses to
 * install a package whose `os`/`cpu` do not match the host, and a cross build
 * must still ship them.
 */
function installNativeCompanions() {
  const cacheDir = path.join(SOURCE_MODULES, '.cache', 'dsh-native')
  let count = 0

  for (const { loader, packages } of NATIVE_COMPANIONS) {
    const loaderDir = resolvePackageDir(loader, SOURCE_ROOT)
    const pins = JSON.parse(readFileSync(path.join(loaderDir, 'package.json'), 'utf-8')).optionalDependencies ?? {}

    for (const name of new Set(Object.values(packages).flat())) {
      const version = pins[name]
      if (!version) throw new Error(`[dsh-runtime] ${loader} does not declare ${name}`)
      const dest = path.join(OUT_DIR, 'node_modules', ...name.split('/'))
      mkdirSync(path.dirname(dest), { recursive: true })

      let hostCopy = null
      try {
        hostCopy = resolvePackageDir(name, loaderDir)
      } catch {
        hostCopy = null
      }
      if (hostCopy && JSON.parse(readFileSync(path.join(hostCopy, 'package.json'), 'utf-8')).version === version) {
        cpSync(hostCopy, dest, { recursive: true, dereference: true })
        count++
        continue
      }

      const tarball = path.join(cacheDir, `${name.replace('/', '__')}-${version}.tgz`)
      if (!existsSync(tarball)) {
        mkdirSync(cacheDir, { recursive: true })
        const packed = execFileSync(
          'npm',
          ['pack', `${name}@${version}`, '--pack-destination', cacheDir, '--silent'],
          { encoding: 'utf-8', shell: process.platform === 'win32' }
        ).trim().split('\n').pop()
        renameSync(path.join(cacheDir, packed), tarball)
      }
      mkdirSync(dest, { recursive: true })
      execFileSync('tar', ['-xzf', tarball, '-C', dest, '--strip-components=1'])
      count++
    }
  }
  log(`native companions planted: ${count} package(s)`)
}

async function build() {
  ensureSourceInstalled()
  assertPluginsInstalled()
  assertExternalsArePrivate()

  rmSync(OUT_DIR, { recursive: true, force: true })
  mkdirSync(path.dirname(OUT_ENTRY), { recursive: true })

  // Written into the source package so esbuild resolves bare specifiers
  // against its node_modules, never the app's.
  const entrySource = path.join(SOURCE_ROOT, '.dsh-runtime-entry.mjs')
  writeFileSync(entrySource, generateEntry(), 'utf-8')

  let metafile
  try {
    ;({ metafile } = await esbuild.build({
      entryPoints: [entrySource],
      outfile: OUT_ENTRY,
      bundle: true,
      platform: 'node',
      format: 'esm',
      target: 'node22',
      external: EXTERNAL_PACKAGES,
      // CommonJS dependencies in the tree (`yaml`, `protobufjs`, ...) reach
      // Node builtins through `require()`. esbuild cannot rewrite those into an
      // ESM output and substitutes a stub that throws on call, so the bundle
      // needs a real `require` in scope — the stub adopts it when one exists.
      banner: {
        js:
          "import { createRequire as __nodeCreateRequire } from 'node:module'\n" +
          'const require = __nodeCreateRequire(import.meta.url)',
      },
      // Not minified on purpose: engine stack traces reaching Halo's logs are
      // the only diagnostic available for a crash inside the child.
      minify: false,
      legalComments: 'none',
      logLevel: quiet ? 'silent' : 'warning',
      metafile: true,
    }))
  } finally {
    rmSync(entrySource, { force: true })
  }

  assertOnlyDeclaredExternals(metafile)
  const code = readFileSync(OUT_ENTRY, 'utf-8')
  assertLazyRequiresDeclared(code)

  const engineVersion = writeManifest()
  installPrivateExternals()
  installNativeCompanions()

  const sizeMB = (Buffer.byteLength(code) / 1024 / 1024).toFixed(1)
  log(
    `built ${RUNTIME_DIR}/${RUNTIME_ENTRY} (${sizeMB} MB, ` +
      `${PLUGIN_PACKAGES.length + HALO_PLUGINS.length} plugins, dsh ${engineVersion})`
  )
}

build().catch((err) => {
  console.error(err.message ?? err)
  if (!optional) process.exit(1)
  rmSync(OUT_DIR, { recursive: true, force: true })
  console.warn('[dsh-runtime] build failed; continuing without the dsh engine (--optional)')
})
