/**
 * Unit tests for resolveModelVision — the one answer the input hint, the
 * backend config and the image fallback all resolve through.
 *
 * The layering is what matters: a per-model override (user setting or a
 * capability the provider catalog declared) must beat the provider's static
 * flag, which must beat the id heuristic. A gateway alias like `public` is
 * unreadable by name, so without the override layer it defaults to
 * vision-capable and images reach a text-only upstream.
 *
 * The parity snapshot below pins the pre-migration production behavior: the
 * expected values were generated by running the RETIRED legacy substring
 * algorithm (NON_VISION_PATTERNS / VISION_KEYWORDS, commit history) over
 * every catalog model id, every JSON preset key, and synthetic ids covering
 * each allowlist/blocklist entry. When the vision data moved into
 * model-capabilities.json, only glm-5.3-flash was allowed to differ (the
 * product fix this migration shipped). If one of these expectations fails,
 * the JSON data drifted and a live model's image handling changed — that is
 * a regression, not a test to update.
 */

import { describe, it, expect } from 'vitest'
import {
  resolveModelVision,
  supportsVisionById
} from '../../../src/shared/constants/model-capabilities'

describe('resolveModelVision', () => {
  it('lets a per-model override win over the id heuristic', () => {
    // `public` is unknown to the heuristic, which defaults to vision-capable.
    const source = {
      modelOverrides: { public: { vision: false } },
      availableModels: [{ id: 'public', name: 'auto' }]
    }
    expect(resolveModelVision(source, 'public')).toBe(false)
  })

  it('lets a per-model override re-enable a blacklisted model id', () => {
    const source = {
      modelOverrides: { 'glm-5.2': { vision: true } },
      availableModels: [{ id: 'glm-5.2', name: 'GLM 5.2' }]
    }
    expect(resolveModelVision(source, 'glm-5.2')).toBe(true)
  })

  it('lets a per-model override win over the provider-declared flag', () => {
    const source = {
      modelOverrides: { 'model-x': { vision: true } },
      availableModels: [{ id: 'model-x', name: 'X', supportsVision: false }]
    }
    expect(resolveModelVision(source, 'model-x')).toBe(true)
  })

  it('falls back to the provider-declared flag when no override exists', () => {
    const source = {
      availableModels: [{ id: 'qwen3.6-35b-a3b', name: 'Qwen', supportsVision: true }]
    }
    expect(resolveModelVision(source, 'qwen3.6-35b-a3b')).toBe(true)
  })

  it('falls back to the id heuristic for a model missing from availableModels', () => {
    const source = { availableModels: [{ id: 'other', name: 'Other' }] }
    expect(resolveModelVision(source, 'deepseek-v4-flash')).toBe(false)
    expect(resolveModelVision(source, 'gpt-4o')).toBe(true)
  })

  it('ignores an override keyed to a different model', () => {
    const source = {
      modelOverrides: { 'glm-5.2': { vision: false } },
      availableModels: [{ id: 'gpt-4o', name: 'GPT-4o' }]
    }
    expect(resolveModelVision(source, 'gpt-4o')).toBe(true)
  })

  it('degrades to the id heuristic without a source', () => {
    expect(resolveModelVision(null, 'deepseek-chat')).toBe(false)
    expect(resolveModelVision(undefined, 'unknown-model')).toBe(true)
  })
})

/**
 * Production parity snapshot — see the file header for provenance.
 * Sources of the ids: every hardcoded catalog entry (shared/constants/
 * providers.ts, zhipu-coding-oauth GLM_MODELS), every `models` key in
 * model-capabilities.json, and synthetic ids exercising each
 * allowlist/blocklist entry including mid-string hits, proxy-prefixed
 * forms, and case variants.
 */
const VISION_TRUE = [
  'claude-sonnet-5', 'claude-fable-5', 'claude-opus-5',
  'claude-opus-4-8', 'claude-opus-4-6', 'claude-haiku-4-5-20251001',
  'gpt-4o', 'gpt-4o-mini', 'o1',
  'o1-mini', 'Pro/moonshotai/Kimi-K2.5', 'qwen3-max',
  'qwen-plus', 'kimi-k2.5', 'kimi-k2',
  'moonshot-v1-128k', 'yi-lightning', 'yi-large',
  'yi-medium', 'step-2', 'step-2-mini',
  'anthropic/claude-opus-4.5', 'openai/gpt-5.2', 'google/gemini-3-pro-preview',
  'qwen/qwen3.5-27b', 'openai/gpt-4o-mini', 'anthropic/claude-sonnet-4-5',
  'google/gemini-2.5-flash', 'meta-llama/llama-4-maverick-17b-128e-instruct', 'meta-llama/llama-4-scout-17b-16e-instruct',
  'Qwen/Qwen3-235B-A22B-Instruct-2507', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', 'grok-4',
  'grok-4.1-fast', 'grok-3', 'qwen3-235b-a22b',
  'qwen3-72b', 'qwen3-32b', 'qwen3-14b',
  'qwen3-8b', 'qwen-turbo', 'qwen-max',
  'qwen-vl-plus', 'qwen-vl-max', 'glm-z1-plus',
  'glm-z1', 'claude-sonnet-5[1m]', 'claude-fable-5[1m]',
  'claude-opus-5[1m]', 'claude-opus-4-8[1m]', 'claude-opus-4-7',
  'claude-opus-4-7[1m]', 'claude-opus-4-6[1m]', 'claude-opus-4-5-20251101',
  'claude-sonnet-4-6', 'claude-sonnet-4-6[1m]', 'claude-sonnet-4-5-20250929',
  'gpt-5.4', 'gpt-6', 'gpt-4.1',
  'gpt-4.1-mini', 'gpt-5', 'o3',
  'o4-mini', 'gemini-2.5-pro', 'gemini-2.5-flash',
  'gemini-2.0-flash', 'grok-3-mini', 'glm-4v-max',
  'qwen2-vl-max', 'pixtral-large', 'paligemma-3',
  'cogvlm-2', 'glm-ocr-pro', 'gpt-4o-vision',
  'my-model-omni', 'acme-multimodal-1', 'x-vision-turbo',
  'vision-ai/somemodel', 'GPT-4O', 'unknown-model',
  'some-future-model-9',
]

const VISION_FALSE = [
  'deepseek-v4-flash', 'deepseek-v4-pro', 'deepseek-chat',
  'deepseek-reasoner', 'Pro/deepseek-ai/DeepSeek-V3', 'Pro/deepseek-ai/DeepSeek-R1',
  'Pro/zai-org/GLM-4.7', 'qwen3-coder', 'glm-4.7',
  'glm-4.7-flash', 'glm-4-plus', 'glm-5.2',
  'glm-5.1', 'glm-5', 'glm-4.6',
  'glm-4.5', 'MiniMax-M2.7', 'MiniMax-M2.1',
  'MiniMax-M1', 'MiniMax-M2.7-highspeed', 'deepseek/deepseek-v3.2',
  'deepseek-ai/deepseek-v4-flash', 'deepseek-ai/deepseek-v4-pro', 'deepseek/deepseek-chat',
  'llama-3.3-70b-versatile', 'mistral-large-2512', 'mistral-medium-3.1',
  'codestral-2508', 'deepseek-ai/DeepSeek-V3', 'accounts/fireworks/models/deepseek-v3p2',
  'accounts/fireworks/models/deepseek-r1-0528', 'accounts/fireworks/models/qwen3-coder-480b-a35b-instruct', 'glm-4.5-air',
  'glm-5-turbo', 'mistral-large-latest', 'deepseek-v5',
  'chatglm-6', 'llama-2-7b', 'llama-3.1-8b',
  'llama-3.3-70b', 'codellama-34b', 'mixtral-8x7b',
  'mistral-large-2', 'mistral-medium-2', 'mistral-nemo-x',
  'codestral-latest', 'qwen-coder-3', 'qwen2.5-coder-32b',
  'qwen3-coder-500b', 'qwen-math-2', 'qwq-32b',
  'phi-2-mini', 'phi-3-mini-x', 'phi-3-small-x',
  'phi-3-medium-x', 'phi-4-mini-x', 'gemma-2-27b',
  'codegemma-7b', 'nemotron-70b', 'minimax-m3',
  'abab-7', 'command-r-plus', 'dbrx-2',
  'olmo-7b', 'starcoder-2', 'solar-10b',
  'mercury-coder', 'lfm-2', 'palmyra-x',
  'internlm2-7b', 'baichuan-7b', 'x-deepseek-y',
  'org-glm-4-turbo', 'test-chatglm-3', 'alias-codestral-x',
  'grok-codestral-hybrid', 'deepseek-proxy/gpt-4o', 'GLM-4.7',
  'DeepSeek-Chat',
]

describe('supportsVisionById — production parity snapshot', () => {
  it('resolves every known vision-capable id to true', () => {
    for (const id of VISION_TRUE) {
      expect(supportsVisionById(id), id).toBe(true)
    }
  })

  it('resolves every known text-only id to false', () => {
    for (const id of VISION_FALSE) {
      expect(supportsVisionById(id), id).toBe(false)
    }
  })

  it('treats absent and empty ids as vision-capable', () => {
    expect(supportsVisionById(undefined)).toBe(true)
    expect(supportsVisionById(null)).toBe(true)
    expect(supportsVisionById('')).toBe(true)
  })
})

describe('glm-5.3 family — the one intended behavior change', () => {
  it('keeps glm-5.3 text-only like the rest of the glm-5 family', () => {
    expect(supportsVisionById('glm-5.3')).toBe(false)
    expect(resolveModelVision(null, 'glm-5.3')).toBe(false)
  })

  it('treats glm-5.3-flash as multimodal via its exact preset entry', () => {
    expect(supportsVisionById('glm-5.3-flash')).toBe(true)
    expect(resolveModelVision(null, 'glm-5.3-flash')).toBe(true)
  })

  it('lets the exact entry beat the glm-5 blocklist entry for the bare id', () => {
    expect(supportsVisionById('GLM-5.3-Flash')).toBe(true)
  })

  it('survives an inert routing prefix — a gateway id is still the same model', () => {
    expect(supportsVisionById('Pro/zai-org/GLM-5.3-Flash')).toBe(true)
    expect(supportsVisionById('zhipu/glm-5.3-flash')).toBe(true)
    expect(supportsVisionById('openrouter/glm-5.3-flash')).toBe(true)
    expect(resolveModelVision(null, 'Pro/zai-org/GLM-5.3-Flash')).toBe(true)
  })

  it('still honors a blocklist signal that lives in the discarded prefix itself', () => {
    // "deepseek-proxy/gpt-4o" carries its own family signal ("deepseek") in
    // the prefix — that must not be erased by the bare "gpt-4o" exact entry.
    expect(supportsVisionById('deepseek-proxy/gpt-4o')).toBe(false)
  })
})
