// Code generated by scripts/gen-gateway-planes.mjs from src/shared/federation/planes.json. DO NOT EDIT.

package wire

// Plane is one outbound priority plane; lower values drain first.
type Plane int

const (
	PlaneControl Plane = iota
	PlaneStream
	PlaneFeed
	PlaneArtifact
	PlaneCount
)

// PlaneNames are the wire names of the planes (the envelope `plane` hint).
var PlaneNames = [PlaneCount]string{"control", "stream", "feed", "artifact"}

// PlaneCapacityFrames bounds each plane queue by frame count.
var PlaneCapacityFrames = [PlaneCount]int{1024, 256, 256, 32}

// PlaneCapacityBytes bounds each plane queue by size (0 = no size bound).
var PlaneCapacityBytes = [PlaneCount]int{0, 0, 4194304, 0}

func (p Plane) String() string {
	if p >= 0 && p < PlaneCount {
		return PlaneNames[p]
	}
	return "unknown"
}

// PlaneByName resolves a wire plane name.
func PlaneByName(name string) (Plane, bool) {
	for i, n := range PlaneNames {
		if n == name {
			return Plane(i), true
		}
	}
	return PlaneControl, false
}
