/**
 * The cordis plugin composition Halo boots the dsh runtime with.
 *
 * Tracks upstream's `sdk-minimal` bundle (`packages/bundle/sdk-minimal`): an
 * explicit kernel that owns every service row rather than layering over
 * `dsh-base`. It departs from that bundle where Halo, not the harness, is the
 * product:
 *   - no DeepSeek telemetry rows (`session-log-deepseek`,
 *     `plugin-package-inventory-deepseek`, `deepseek-llm-api-extensions`):
 *     they upload session logs and plugin inventories to DeepSeek whichever
 *     vendor the user chose;
 *   - no `dsh-sdk-app` startup provider: the entry generated by
 *     `runtimes/dsh/build.mjs` owns the process lifecycle;
 *   - sandbox, skill, web and subagent rows, which are Halo features the
 *     minimal kernel does not carry.
 *
 * Composition is also the only enforcement point Halo has over what the model
 * may do: the runtime exposes no per-call approval channel and no tool filter
 * outside the child, so a tool a caller must not use has to be a tool the
 * runtime never registers — see `TOOL_PLUGINS`.
 *
 * stdout is reserved for JSON-RPC, so nothing here may write to it: no console
 * logger, no terminal UI, no approval UI.
 *
 * Config values that vary per launch are read from the child env rather than
 * interpolated into the text, so this document is a constant and one runtime's
 * settings can never leak into another's. `!!js` expressions are evaluated by
 * the cordis loader inside the child.
 *
 * Plugins are named `cordis:<id>` rather than by package. That prefix is the
 * loader's escape hatch for plugins the host supplies directly: it reads
 * `loader.builtins[id]` and never resolves a module from disk. The engine ships
 * as one bundled file with every plugin registered there (see
 * `runtimes/dsh/manifest.cjs`), so a package name here would send the
 * loader looking for a `node_modules` tree the packaged app no longer has. Any
 * id used below must exist in that manifest — enforced by
 * `tests/unit/services/agent/dsh/runtime-manifest.test.ts`.
 */

import { createHash } from 'crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import path from 'path'
import { buildDshMcpComposition, DSH_MCP_SERVERS_ENV } from './mcp-plugins'
import type { ExternalMcpServer } from '../../mcp/types'

/**
 * Everything that is not a model-facing tool: services, session plumbing, and
 * the backends the tool plugins dispatch through. Row order carries no load
 * semantics — the loader activates on service availability — so the grouping
 * is for readers only.
 */
const BASE_PLUGINS = `# Generated by Halo. Edits are overwritten on every launch.
# stdout is reserved for JSON-RPC: no console logger, no terminal UI.

- id: sdk-jsonrpc-server
  name: 'cordis:dsh-sdk-jsonrpc-server'

# Halo's own plugin (./plugins/assistant-stream.ts): the SDK server forwards
# session-log events only, and live token chunks are not log events.
- id: halo-assistant-stream
  name: 'cordis:halo-assistant-stream'

- id: llm
  name: 'cordis:dsh-llm'

# defaultContextWindow is the capacity every consumer downstream reads: the
# token meter reports against it and compaction fires at a ratio of it. The
# plugin's own default is DeepSeek's 1M, which on any smaller model puts the
# threshold past the real window — nothing compacts and the provider rejects
# the turn instead. Halo's resolved capability for the active model rides in.
#
# The shipped model catalogue is emptied for the same reason: an id listed
# there carries its own window, which silently outranks the value above for
# exactly the models the list happens to name. Halo's capability table — user
# overridable in Settings — has to be the only authority, or one model answers
# to Settings and its neighbour does not. An unlisted model still routes, as a
# text-only model with no in-history prompt or tool updates — DeepSeek-specific
# request forms other gateways would reject. The one entry Halo adds is the
# active model when Halo judges it vision-capable: it declares image input and
# nothing else, so the window above still applies.
#
# The output cap is deliberately not set here: it belongs to one agent rather
# than to the route, and travels in \`initialize\` (see \`../options.ts\`).
#
# The adapter speaks the Anthropic Messages API, and DEEPSEEK_BASE_URL points it
# at Halo's compat router, which owns the translation to the source's dialect.
# Reasoning effort stays at the adapter default \`high\`: \`max\` is not a value
# every Messages-compatible endpoint accepts in \`output_config.effort\`.
- id: llm-deepseek
  name: 'cordis:dsh-llm-deepseek-api-key'
  config:
    thinking: enabled
    defaultContextWindow: !!js "Number(process.env.DSH_CONTEXT_WINDOW ?? 1000000)"
    models: !!js "JSON.parse(process.env.DSH_MODEL_CATALOG ?? '[]')"

# Retries transient provider failures (rate limit, 5xx, timeout, transport,
# empty response) at step boundaries instead of ending the turn. The policy is
# the adapter's default \`retryPolicy\`.
- id: llm-retry
  name: 'cordis:dsh-llm-retry'

- id: credentials
  name: 'cordis:dsh-credentials-local'

# Where a prompt's images live: the SDK server admits each inline image here
# (normalized through the runtime's private sharp) before the model sees it.
# Stored under the runtime's home, which is Halo's directory (DSH_HOME).
- id: attachment-local
  name: 'cordis:dsh-attachment-local'

- id: session
  name: 'cordis:dsh-session'

# No persistence backend (and so no checkpoint policy). The SDK protocol can
# only create a session, never resume one — \`session/prompt\` on an id a
# backend already holds fails with "already exists" — so a persisted log would
# be write-only: never read back, never pruned, and fsynced before every model
# request and tool call. Halo keeps the conversation transcript itself.

# Shared projection registry the sandbox policy, terminal backend, token meter,
# todo and subagent tools, retry executor and agent loop fold state through.
- id: session-projection
  name: 'cordis:dsh-session-projection'

- id: agent
  name: 'cordis:dsh-agent'

# The route every SDK-created agent runs on. initialize() overrides it per
# runtime; this is the value used if a session is created before the handshake.
- id: agent-default-model
  name: 'cordis:dsh-agent-default-model'
  config:
    provider: deepseek-official
    model: deepseek-v4-flash

# Empty: sessions are created on demand by session/prompt, not at startup.
- id: agent-loop
  name: 'cordis:dsh-agent-loop'
  config:
    agents: []

- id: tools
  name: 'cordis:dsh-tools'

# Halo's identity layer arrives as the persona prefix, so the harness's own
# "You are an AI agent powered by DeepSeek Harness." opener is switched off:
# the model would otherwise be told two different things about who it is.
- id: system-prompt
  name: 'cordis:dsh-system-prompt'
  config:
    includeHarnessIdentity: false
    personaPrefix: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a helpful assistant.'

# Skill discovery. Halo owns where skills live and passes both of its roots
# explicitly, so the provider's own \`~/.dsh\` and \`~/.agents\` conventions are
# switched off: a skill the default engine cannot see must not appear here
# either, or the two engines disagree about what is installed.
#
# Only skills whose SKILL.md carries a \`name\` and a \`description\`, with the
# name in kebab-case, are loaded — a narrower contract than Claude Code, which
# defaults a missing name to the directory name. The provider warns and skips
# the rest, and that warning is not visible: stdout belongs to JSON-RPC and the
# composition mounts no logger.
- id: skill
  name: 'cordis:dsh-skill'

- id: skill-filesystem
  name: 'cordis:dsh-skill-filesystem'
  config:
    includeDefaultRoots: false
    customSkillDirs: !!js "JSON.parse(process.env.DSH_SKILL_DIRS ?? '[]')"
    watch: true

- id: subprocess
  name: 'cordis:dsh-subprocess-local'

- id: sandbox
  name: 'cordis:dsh-sandbox-local'

- id: sandbox-policy
  name: 'cordis:dsh-sandbox-policy'
  config:
    mode: workspace-write
    workspaceRoot: !!js process.env.DSH_CWD ?? process.cwd()

# Provides the 'fs' service by wrapping the local backend; mounting
# dsh-fs-local alongside it double-registers that service and fails the boot.
- id: fs-sandbox
  name: 'cordis:dsh-fs-sandbox'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()

- id: fs-observation-policy
  name: 'cordis:dsh-fs-observation-policy'

# One-shot shell backend. bash-local provides the 'shell' service by extending
# the executor base; mounting dsh-shell alongside it double-registers and fails
# the boot, the same shape as fs-sandbox above.
- id: bash-local
  name: 'cordis:dsh-bash-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 120000

- id: shell-env
  name: 'cordis:dsh-shell-env'

# Interactive PTY sessions, spawned through dsh-subprocess-local's pinned
# node-pty (see PRIVATE_EXTERNALS in runtimes/dsh/manifest.cjs).
- id: terminal
  name: 'cordis:dsh-terminal'

# The dialect decides argv, environment and prompt detection, so it follows the
# shell Halo resolved: bash when there is one, otherwise the plugin's PowerShell
# dialect — the Windows install with no bash, where a POSIX default would spawn
# nothing at all. An empty path selects the dialect's own executable.
- id: terminal-bash
  name: 'cordis:dsh-terminal-bash'
  config:
    shellDialect: !!js "process.env.DSH_SHELL_PATH ? 'bash' : 'pwsh'"
    shellPath: !!js process.env.DSH_SHELL_PATH ?? ''

# Search is a Messages call carrying a server-side search tool. It reads its
# own endpoint variable, which Halo points at the compat router exactly like the
# conversation route: the default is DeepSeek's API, and the credential it would
# send there is Halo's encoded backend descriptor for whatever source is active.
- id: web
  name: 'cordis:dsh-web'

- id: web-fetch-http
  name: 'cordis:dsh-web-fetch-http'

- id: web-search-deepseek
  name: 'cordis:dsh-web-search-deepseek'

- id: subagent
  name: 'cordis:dsh-subagent'

- id: subagent-spawn-in-process
  name: 'cordis:dsh-subagent-spawn-in-process'
  config:
    providerName: spawn

- id: token-meter
  name: 'cordis:dsh-token-meter'

# A request over the adapter's image budget fails with IMAGE_OFFLOAD_REQUIRED;
# this replaces the oldest images with placeholders and retries.
- id: image-offload
  name: 'cordis:dsh-compaction-image-offload'

# Compaction fires at min(0.8 × window, window − output cap − headroom). The
# plugin's 64K headroom is sized for DeepSeek's 1M window and, on the 128K-class
# windows most sources serve, leaves little or no positive threshold — at none,
# proactive compaction switches itself off. The headroom only has to hold the
# summary request, so it is sized from the summary's own output cap.
- id: compaction-basic
  name: 'cordis:dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    headroomTokens: 16384
    retainRatio: 0.16
    maxTokens: 8192
    compactionRetries: 1
`

interface ToolPlugin {
  /** The row to mount for this caller, or null to leave the block out. */
  render(permits: (tool: string) => boolean): string | null
}

/**
 * A block dsh registers as one group. Mounted only when the caller may use
 * every Halo tool it stands in for: the plugin offers no way to split the
 * group, and withholding one Halo cannot fully permit is the only direction
 * that cannot over-grant.
 */
function bundle(grants: readonly string[], yaml: string): ToolPlugin {
  return { render: (permits) => (grants.every(permits) ? yaml : null) }
}

/**
 * The model-facing tools, each paired with what permitting it means in Halo's
 * vocabulary. The pairing lives next to the row it gates so the two cannot
 * drift into describing different compositions.
 */
const TOOL_PLUGINS: readonly ToolPlugin[] = [
  // read, write, edit, read_image.
  bundle(
    ['Read', 'Write', 'Edit'],
    `- id: tool-fs
  name: 'cordis:dsh-tool-fs'
`
  ),
  // glob / grep. Ships its own ripgrep binary, so it needs nothing from the
  // host. sampleOverCapGlobResults has no default: spreading an over-cap glob
  // across top-level entries beats truncating it, which would hide whole
  // directories.
  bundle(
    ['Glob', 'Grep'],
    `- id: tool-fs-search
  name: 'cordis:dsh-tool-fs-search'
  config:
    sampleOverCapGlobResults: true
`
  ),
  bundle(
    ['Edit'],
    `- id: tool-str-replace-editor
  name: 'cordis:dsh-tool-str-replace-editor'
`
  ),
  bundle(
    ['TodoWrite'],
    `- id: tool-todo
  name: 'cordis:dsh-tool-todo'
  config:
    allowParallelInProgress: true
`
  ),
  // Background is off: a job finishing after Halo's turn has closed wakes the
  // session on its own, and nothing outside a prompt's interval reaches the
  // timeline. Without a job registry mounted the tool is foreground-only anyway.
  bundle(
    ['Bash'],
    `- id: tool-bash
  name: 'cordis:dsh-tool-bash'
  config:
    enableRunInBackground: false
`
  ),
  // The six terminal_* tools drive a live shell, so permitting them is
  // permitting shell access however Halo happens to name it.
  bundle(
    ['Bash'],
    `- id: tool-terminal
  name: 'cordis:dsh-tool-terminal'
  config:
    enableRunInBackground: false
`
  ),
  {
    // The one block that narrows instead of dropping out: this plugin decides
    // each tool's registration from config. It matters because Halo denies
    // WebSearch by default, and a bundled row would take web_fetch away from
    // every ordinary user to honour that.
    render: (permits) => {
      const search = permits('WebSearch')
      const fetch = permits('WebFetch')
      if (!search && !fetch) return null
      return `- id: tool-web
  name: 'cordis:dsh-tool-web'
  config:
    search: ${search}
    fetch: ${fetch}
`
    },
  },
  // The `skill` tool loads a skill body into the turn. Without it the provider
  // above still discovers skills, but nothing can open one.
  bundle(
    ['Skill'],
    `- id: tool-skill
  name: 'cordis:dsh-tool-skill'
`
  ),
  // A child agent draws from the same registry, so a tool omitted above is out
  // of its reach too.
  bundle(
    ['Task'],
    `- id: tool-subagent
  name: 'cordis:dsh-tool-subagent'
  config:
    provider: spawn
    toolName: subagent
    backgroundMode: one-shot
`
  ),
]

export interface CordisComposition {
  /**
   * Halo tool names the session may not use. Undefined means unrestricted —
   * the shape Halo's own callers pass; a guest session arrives with the
   * inverted whitelist its policy produced.
   */
  disallowedTools?: readonly string[]
  /** MCP servers to connect, keyed by Halo's server id. */
  mcpServers?: Record<string, ExternalMcpServer>
  /** Working directory for an MCP server that declares none. */
  workDir?: string
}

export interface MaterializedCordisConfig {
  /** Absolute path of the written composition. */
  path: string
  /**
   * Environment the composition reads at load. Merged into the child env by
   * the launch spec; the values are secrets and ephemeral ports, which is why
   * they are not in the file.
   */
  env: Record<string, string>
  /** MCP server names the composition connects, in row order. */
  mcpServers: string[]
}

/**
 * Write the composition into `dir` and describe what the child needs to load it.
 *
 * Generated rather than shipped as a static asset: a static file would have to
 * survive `electron-vite`'s main-process bundle and be re-declared in the
 * packaging file list, and nothing would keep it in sync with this module.
 * Plugin names resolve out of the runtime's own builtins rather than relative
 * to this file, so Halo's data directory is a valid home for it.
 *
 * The filename carries a digest of the content because the loader watches the
 * path it booted from and hot-reloads it. Sessions with different tool sets
 * share one data directory, so a fixed name would let a later launch rewrite
 * the document a running child is still watching — handing it another
 * session's permissions. That argument is why no per-session value may be
 * interpolated into the text: two sessions differing only in an MCP token or a
 * bridge port must keep sharing one file, and the differing values ride in the
 * returned environment instead.
 */
export function materializeCordisConfig(
  dir: string,
  composition: CordisComposition = {}
): MaterializedCordisConfig {
  const denied = new Set(composition.disallowedTools ?? [])
  const mounted = TOOL_PLUGINS.map((plugin) => plugin.render((tool) => !denied.has(tool))).filter(
    (yaml): yaml is string => yaml !== null
  )
  const mcp = buildDshMcpComposition(
    composition.mcpServers ?? {},
    composition.workDir ?? process.cwd()
  )
  for (const { name, reason } of mcp.skipped) {
    console.warn(`[Dsh][runtime] MCP server '${name}' not mounted: ${reason}`)
  }

  const text = [BASE_PLUGINS, mounted.join('\n'), mcp.yaml].filter(Boolean).join('\n')
  const digest = createHash('sha256').update(text).digest('hex').slice(0, 12)
  const configPath = path.join(dir, `halo.cordis.${digest}.yml`)
  const env = { [DSH_MCP_SERVERS_ENV]: mcp.env }
  mkdirSync(dir, { recursive: true })

  // Skip the write when unchanged: the loader watches this path for HMR.
  let existing: string | null = null
  try {
    existing = readFileSync(configPath, 'utf-8')
  } catch {
    existing = null
  }
  if (existing === text) return { path: configPath, env, mcpServers: mcp.mounted }

  writeFileSync(configPath, text, 'utf-8')
  console.log(
    `[Dsh][runtime] wrote cordis config path=${configPath} bytes=${text.length} ` +
      `toolPlugins=${mounted.length}/${TOOL_PLUGINS.length} mcpServers=${mcp.mounted.length}`
  )
  return { path: configPath, env, mcpServers: mcp.mounted }
}
