/**
 * The cordis plugin composition Halo boots the dsh runtime with.
 *
 * Derived from `examples/jsonrpc-agent/cordis.yml`, with one deliberate
 * departure forced by what is actually installable from npm at 0.1.0-rc.6:
 * `@deepseek-ai/dsh-agent-spine-demo` is unusable — six of its peer
 * dependencies (dsh-paths, dsh-workspace-context, dsh-tool-tasks,
 * dsh-tasks-local, dsh-bash-env, dsh-goal-session) are not published. The spine
 * is composed here from the primitives the shipped `@deepseek-ai/dsh-base`
 * bundle carries instead (agent, agent-loop, tools, system-prompt).
 *
 * Two tools the upstream CLI offers are absent because their packages cannot
 * resolve: `tool-pwsh` imports the unpublished `@deepseek-ai/dsh-bash`, and
 * `tool-bash-persistent` needs the unpublished `@deepseek-ai/dsh-pty`. The
 * persistent-shell need is served by the terminal tools below instead.
 *
 * Composition is also the only enforcement point Halo has over what the model
 * may do: the runtime exposes no per-call approval channel and no tool filter
 * outside the child, so a tool a caller must not use has to be a tool the
 * runtime never registers — see `TOOL_PLUGINS`.
 *
 * stdout is reserved for JSON-RPC, so nothing here may write to it: no console
 * logger, no terminal UI, no approval UI.
 *
 * Config values that vary per launch are read from the child env rather than
 * interpolated into the text, so this document is a constant and one runtime's
 * settings can never leak into another's. `!!js` expressions are evaluated by
 * the cordis loader inside the child.
 */

import { createHash } from 'crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'fs'
import path from 'path'
import { buildDshMcpComposition, DSH_MCP_SERVERS_ENV } from './mcp-plugins'
import type { ExternalMcpServer } from '../../mcp/types'

/**
 * Everything that is not a model-facing tool: services, session plumbing, and
 * the backends the tool plugins dispatch through. Row order carries no load
 * semantics — the loader activates on service availability — so the grouping
 * is for readers only.
 */
const BASE_PLUGINS = `# Generated by Halo. Edits are overwritten on every launch.
# stdout is reserved for JSON-RPC: no console logger, no terminal UI.

- id: sdk-jsonrpc-server
  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'

- id: llm
  name: '@deepseek-ai/dsh-llm'

- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
    thinking: enabled
    reasoningEffort: max

- id: credentials
  name: '@deepseek-ai/dsh-credentials-local'

- id: session
  name: '@deepseek-ai/dsh-session'

- id: session-persistence-jsonl
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT ?? './.sessions'
    compression: none

- id: session-projection
  name: '@deepseek-ai/dsh-session-projection'

- id: session-checkpoint-policy
  name: '@deepseek-ai/dsh-session-checkpoint-policy'

- id: agent
  name: '@deepseek-ai/dsh-agent'

# The route every SDK-created agent runs on. initialize() overrides it per
# runtime; this is the value used if a session is created before the handshake.
- id: agent-default-model
  name: '@deepseek-ai/dsh-agent-default-model'
  config:
    provider: deepseek-official
    model: deepseek-v4-flash

# Empty: sessions are created on demand by session/prompt, not at startup.
- id: agent-loop
  name: '@deepseek-ai/dsh-agent-loop'
  config:
    agents: []

- id: tools
  name: '@deepseek-ai/dsh-tools'

- id: system-prompt
  name: '@deepseek-ai/dsh-system-prompt'
  config:
    persona: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a helpful assistant.'

# Skill discovery. Halo owns where skills live and passes both of its roots
# explicitly, so the provider's own \`~/.dsh\` and \`~/.agents\` conventions are
# switched off: a skill the default engine cannot see must not appear here
# either, or the two engines disagree about what is installed.
#
# Only skills whose SKILL.md carries a \`name\` and a \`description\`, with the
# name in kebab-case, are loaded — a narrower contract than Claude Code, which
# defaults a missing name to the directory name. The provider warns and skips
# the rest, and that warning is not visible: stdout belongs to JSON-RPC and the
# composition mounts no logger.
- id: skill
  name: '@deepseek-ai/dsh-skill'

- id: skill-filesystem
  name: '@deepseek-ai/dsh-skill-filesystem'
  config:
    includeDefaultRoots: false
    customSkillDirs: !!js "JSON.parse(process.env.DSH_SKILL_DIRS ?? '[]')"
    watch: true

- id: subprocess
  name: '@deepseek-ai/dsh-subprocess-local'

- id: sandbox
  name: '@deepseek-ai/dsh-sandbox-local'

- id: sandbox-policy
  name: '@deepseek-ai/dsh-sandbox-policy'
  config:
    mode: workspace-write
    workspaceRoot: !!js process.env.DSH_CWD ?? process.cwd()

# Provides the 'fs' service by wrapping the local backend; mounting
# dsh-fs-local alongside it double-registers that service and fails the boot.
- id: fs-sandbox
  name: '@deepseek-ai/dsh-fs-sandbox'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()

- id: fs-observation-policy
  name: '@deepseek-ai/dsh-fs-observation-policy'

# One-shot shell backend. bash-local provides the 'shell' service by extending
# the executor base; mounting dsh-shell alongside it double-registers and fails
# the boot, the same shape as fs-sandbox above.
- id: bash-local
  name: '@deepseek-ai/dsh-bash-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 120000

- id: shell-env
  name: '@deepseek-ai/dsh-shell-env'

# Interactive PTY sessions. The backend spawns through dsh-subprocess-local,
# whose node-pty prebuilds cover darwin and win32 but not linux.
- id: terminal
  name: '@deepseek-ai/dsh-terminal'

# Path and arguments are one choice, so both read the same variable: PowerShell
# is the fallback for a Windows install with no bash, where the plugin's own
# POSIX default would spawn nothing at all.
- id: terminal-bash
  name: '@deepseek-ai/dsh-terminal-bash'
  config:
    shellPath: !!js process.env.DSH_SHELL_PATH ?? 'powershell.exe'
    shellArgs: !!js "process.env.DSH_SHELL_PATH ? ['--noprofile', '--norc', '-i'] : ['-NoLogo', '-NoProfile']"

# Search speaks the Anthropic Messages API, so it reads its own endpoint
# variable and fails per call — not at boot — when the active source is not
# DeepSeek.
- id: web
  name: '@deepseek-ai/dsh-web'

- id: web-fetch-http
  name: '@deepseek-ai/dsh-web-fetch-http'

- id: web-search-deepseek
  name: '@deepseek-ai/dsh-web-search-deepseek'

- id: subagent
  name: '@deepseek-ai/dsh-subagent'

- id: subagent-spawn-in-process
  name: '@deepseek-ai/dsh-subagent-spawn-in-process'
  config:
    providerName: spawn

- id: token-meter
  name: '@deepseek-ai/dsh-token-meter'

- id: compaction-basic
  name: '@deepseek-ai/dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    retainRatio: 0.16
    maxTokens: 8192
    compactionRetries: 1
`

interface ToolPlugin {
  /** The row to mount for this caller, or null to leave the block out. */
  render(permits: (tool: string) => boolean): string | null
}

/**
 * A block dsh registers as one group. Mounted only when the caller may use
 * every Halo tool it stands in for: the plugin offers no way to split the
 * group, and withholding one Halo cannot fully permit is the only direction
 * that cannot over-grant.
 */
function bundle(grants: readonly string[], yaml: string): ToolPlugin {
  return { render: (permits) => (grants.every(permits) ? yaml : null) }
}

/**
 * The model-facing tools, each paired with what permitting it means in Halo's
 * vocabulary. The pairing lives next to the row it gates so the two cannot
 * drift into describing different compositions.
 */
const TOOL_PLUGINS: readonly ToolPlugin[] = [
  // read, write, edit, read_image.
  bundle(
    ['Read', 'Write', 'Edit'],
    `- id: tool-fs
  name: '@deepseek-ai/dsh-tool-fs'
`
  ),
  // glob / grep. Ships its own ripgrep binary, so it needs nothing from the
  // host. sampleOverCapGlobResults has no default: spreading an over-cap glob
  // across top-level entries beats truncating it, which would hide whole
  // directories.
  bundle(
    ['Glob', 'Grep'],
    `- id: tool-fs-search
  name: '@deepseek-ai/dsh-tool-fs-search'
  config:
    sampleOverCapGlobResults: true
`
  ),
  bundle(
    ['Edit'],
    `- id: tool-str-replace-editor
  name: '@deepseek-ai/dsh-tool-str-replace-editor'
`
  ),
  bundle(
    ['TodoWrite'],
    `- id: tool-todo
  name: '@deepseek-ai/dsh-tool-todo'
  config:
    allowParallelInProgress: true
`
  ),
  // Background is off: it hands the model a job id, and the tools that read
  // and kill a job live in a package that does not resolve from npm yet.
  bundle(
    ['Bash'],
    `- id: tool-bash
  name: '@deepseek-ai/dsh-tool-bash'
  config:
    enableRunInBackground: false
`
  ),
  // The six terminal_* tools drive a live shell, so permitting them is
  // permitting shell access however Halo happens to name it.
  bundle(
    ['Bash'],
    `- id: tool-terminal
  name: '@deepseek-ai/dsh-tool-terminal'
  config:
    enableRunInBackground: false
`
  ),
  {
    // The one block that narrows instead of dropping out: this plugin decides
    // each tool's registration from config. It matters because Halo denies
    // WebSearch by default, and a bundled row would take web_fetch away from
    // every ordinary user to honour that.
    render: (permits) => {
      const search = permits('WebSearch')
      const fetch = permits('WebFetch')
      if (!search && !fetch) return null
      return `- id: tool-web
  name: '@deepseek-ai/dsh-tool-web'
  config:
    search: ${search}
    fetch: ${fetch}
`
    },
  },
  // The `skill` tool loads a skill body into the turn. Without it the provider
  // above still discovers skills, but nothing can open one.
  bundle(
    ['Skill'],
    `- id: tool-skill
  name: '@deepseek-ai/dsh-tool-skill'
`
  ),
  // A child agent draws from the same registry, so a tool omitted above is out
  // of its reach too.
  bundle(
    ['Task'],
    `- id: tool-subagent
  name: '@deepseek-ai/dsh-tool-subagent'
  config:
    provider: spawn
    toolName: subagent
    backgroundMode: one-shot
`
  ),
]

export interface CordisComposition {
  /**
   * Halo tool names the session may not use. Undefined means unrestricted —
   * the shape Halo's own callers pass; a guest session arrives with the
   * inverted whitelist its policy produced.
   */
  disallowedTools?: readonly string[]
  /** MCP servers to connect, keyed by Halo's server id. */
  mcpServers?: Record<string, ExternalMcpServer>
  /** Working directory for an MCP server that declares none. */
  workDir?: string
}

export interface MaterializedCordisConfig {
  /** Absolute path of the written composition. */
  path: string
  /**
   * Environment the composition reads at load. Merged into the child env by
   * the launch spec; the values are secrets and ephemeral ports, which is why
   * they are not in the file.
   */
  env: Record<string, string>
  /** MCP server names the composition connects, in row order. */
  mcpServers: string[]
}

/**
 * Write the composition into `dir` and describe what the child needs to load it.
 *
 * Generated rather than shipped as a static asset: a static file would have to
 * survive `electron-vite`'s main-process bundle and be re-declared in the
 * packaging file list, and nothing would keep it in sync with this module. The
 * runtime entry anchors plugin resolution to the installed package tree (see
 * `./resolve.ts`), so the config does not need to live near `node_modules` and
 * Halo's own data directory is a valid home for it.
 *
 * The filename carries a digest of the content because the loader watches the
 * path it booted from and hot-reloads it. Sessions with different tool sets
 * share one data directory, so a fixed name would let a later launch rewrite
 * the document a running child is still watching — handing it another
 * session's permissions. That argument is why no per-session value may be
 * interpolated into the text: two sessions differing only in an MCP token or a
 * bridge port must keep sharing one file, and the differing values ride in the
 * returned environment instead.
 */
export function materializeCordisConfig(
  dir: string,
  composition: CordisComposition = {}
): MaterializedCordisConfig {
  const denied = new Set(composition.disallowedTools ?? [])
  const mounted = TOOL_PLUGINS.map((plugin) => plugin.render((tool) => !denied.has(tool))).filter(
    (yaml): yaml is string => yaml !== null
  )
  const mcp = buildDshMcpComposition(
    composition.mcpServers ?? {},
    composition.workDir ?? process.cwd()
  )
  for (const { name, reason } of mcp.skipped) {
    console.warn(`[Dsh][runtime] MCP server '${name}' not mounted: ${reason}`)
  }

  const text = [BASE_PLUGINS, mounted.join('\n'), mcp.yaml].filter(Boolean).join('\n')
  const digest = createHash('sha256').update(text).digest('hex').slice(0, 12)
  const configPath = path.join(dir, `halo.cordis.${digest}.yml`)
  const env = { [DSH_MCP_SERVERS_ENV]: mcp.env }
  mkdirSync(dir, { recursive: true })

  // Skip the write when unchanged: the loader watches this path for HMR.
  let existing: string | null = null
  try {
    existing = readFileSync(configPath, 'utf-8')
  } catch {
    existing = null
  }
  if (existing === text) return { path: configPath, env, mcpServers: mcp.mounted }

  writeFileSync(configPath, text, 'utf-8')
  console.log(
    `[Dsh][runtime] wrote cordis config path=${configPath} bytes=${text.length} ` +
      `toolPlugins=${mounted.length}/${TOOL_PLUGINS.length} mcpServers=${mcp.mounted.length}`
  )
  return { path: configPath, env, mcpServers: mcp.mounted }
}
