/**
 * Bundled Office library runtime for agent sessions.
 *
 * The app ships a locked set of pure-JS office libraries (exceljs, docx,
 * pptxgenjs, mammoth, pdf-lib, ...) under resources/office-runtime/node_modules
 * (materialized at build time by scripts/prepare-office-runtime.mjs). This
 * module exposes them to the agent's subprocesses with zero user setup:
 *
 *   - a `halo-node` shim (sh / .cmd), generated into userData, that execs the
 *     Electron binary as Node with the bundled node_modules on NODE_PATH —
 *     skills invoke `halo-node script.js` without any installed Node.js
 *   - `applyOfficeRuntimeEnv()` appends the shim dir to the SDK subprocess PATH
 *     so `halo-node` resolves, and nothing else leaks into the environment
 *
 * The shim bakes absolute paths (Electron binary, modules dir); it is
 * regenerated whenever the rendered content differs from what is on disk, so
 * app updates that move the binary heal on next use. It is written to userData
 * rather than into the app bundle on purpose: writing inside a signed .app
 * invalidates the signature and trips Gatekeeper. All failure paths log and
 * degrade — a missing runtime must never break chat.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { delimiter, join } from 'path'
import { execFile } from 'child_process'
import { app } from 'electron'
// Reaches past the services/agent barrel, which is a known violation, because
// routing through it closes a cycle: agent/index -> send-message -> sdk-config ->
// office-runtime -> here. The resolution is to move this lookup out of the agent
// service — it is pure execPath arithmetic with no agent domain in it, and five
// modules across three areas already import it from this same internal file.
import { getHeadlessElectronPath } from '../agent/helpers'

/** Cached per process: paths are stable for the lifetime of the app. */
let cachedShimDir: string | null | undefined
let missingRuntimeLogged = false

/** Bundled node_modules dir, resolved for dev and packaged (ocr/engine.ts pattern). */
export function getOfficeModulesDir(): string | null {
  const candidates = app.isPackaged
    ? [join(process.resourcesPath, 'office-runtime', 'node_modules')]
    : [
        join(app.getAppPath(), 'resources', 'office-runtime', 'node_modules'),
        join(process.cwd(), 'resources', 'office-runtime', 'node_modules'),
      ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  return null
}

/**
 * Bundled fonts dir (sibling of node_modules), or null when absent. Ships
 * Noto Sans SC for CJK PDF embedding; exposed as HALO_OFFICE_FONTS_DIR.
 */
export function getOfficeFontsDir(): string | null {
  const modulesDir = getOfficeModulesDir()
  if (!modulesDir) return null
  const fontsDir = join(modulesDir, '..', 'fonts')
  return existsSync(fontsDir) ? fontsDir : null
}

/**
 * POSIX-sh shim. Also emitted on Windows (extensionless, next to the .cmd):
 * Git Bash — the agent's shell there — does not resolve a bare `halo-node`
 * to `halo-node.cmd`, while cmd.exe ignores the extensionless file, so both
 * variants coexist without conflict. NODE_PATH is joined with the delimiter
 * Node parses on the target OS (';' on Windows even under an MSYS shell).
 */
function renderShimSh(electronPath: string, modulesDir: string, nodePathDelimiter: string): string {
  return [
    '#!/bin/sh',
    '# Generated by Halo (office-runtime). Do not edit — regenerated on app updates.',
    'export ELECTRON_RUN_AS_NODE=1',
    'export ELECTRON_NO_ATTACH_CONSOLE=1',
    `if [ -n "$NODE_PATH" ]; then`,
    `  export NODE_PATH="$NODE_PATH${nodePathDelimiter}${modulesDir}"`,
    'else',
    `  export NODE_PATH="${modulesDir}"`,
    'fi',
    `exec "${electronPath}" "$@"`,
    '',
  ].join('\n')
}

function renderShimCmd(electronPath: string, modulesDir: string): string {
  return [
    '@echo off',
    'rem Generated by Halo (office-runtime). Do not edit - regenerated on app updates.',
    'set ELECTRON_RUN_AS_NODE=1',
    'set ELECTRON_NO_ATTACH_CONSOLE=1',
    `if defined NODE_PATH (set "NODE_PATH=%NODE_PATH%;${modulesDir}") else (set "NODE_PATH=${modulesDir}")`,
    `"${electronPath}" %*`,
    'exit /b %ERRORLEVEL%',
    '',
  ].join('\r\n')
}

/** Write `content` to `file` only when it differs; returns true when written. */
function writeIfChanged(file: string, content: string): boolean {
  try {
    if (existsSync(file) && readFileSync(file, 'utf-8') === content) return false
  } catch {
    // Unreadable existing file — fall through and rewrite it.
  }
  writeFileSync(file, content, 'utf-8')
  return true
}

/**
 * Ensure the halo-node shim exists and points at the current Electron binary.
 * Returns the shim's directory (for PATH), or null when the bundled runtime is
 * absent (dev checkout without the prepare step) or generation failed.
 */
export function ensureOfficeRuntimeShim(): string | null {
  if (cachedShimDir !== undefined) return cachedShimDir

  const modulesDir = getOfficeModulesDir()
  if (!modulesDir) {
    if (!missingRuntimeLogged) {
      missingRuntimeLogged = true
      console.log(
        '[OfficeRuntime] Bundled runtime not found (run scripts/prepare-office-runtime.mjs); ' +
        'halo-node shim disabled for this session.'
      )
    }
    cachedShimDir = null
    return null
  }

  try {
    const binDir = join(app.getPath('userData'), 'office-runtime', 'bin')
    mkdirSync(binDir, { recursive: true })

    // macOS uses the LSUIElement Helper binary so shim invocations never
    // register Dock icons; other platforms use the main binary directly.
    const electronPath = getHeadlessElectronPath()

    if (process.platform === 'win32') {
      writeIfChanged(join(binDir, 'halo-node.cmd'), renderShimCmd(electronPath, modulesDir))
      // Extensionless sh twin for Git Bash sessions; chmod is a no-op on NTFS.
      writeIfChanged(join(binDir, 'halo-node'), renderShimSh(electronPath, modulesDir, ';'))
    } else {
      const shimPath = join(binDir, 'halo-node')
      const rewritten = writeIfChanged(shimPath, renderShimSh(electronPath, modulesDir, ':'))
      if (rewritten) chmodSync(shimPath, 0o755)
    }

    // Companion script for the startup self-check: a file avoids `-e` quoting
    // differences between sh and cmd.
    writeIfChanged(
      join(binDir, 'self-check.cjs'),
      "require('exceljs');require('docx');console.log('office-runtime-ok');\n"
    )

    cachedShimDir = binDir
    return binDir
  } catch (err) {
    console.error('[OfficeRuntime] Failed to generate halo-node shim; degrading:', err)
    cachedShimDir = null
    return null
  }
}

/**
 * Merge the office runtime into an SDK subprocess env: make `halo-node`
 * resolvable, and point skills at the bundled fonts. No-op with a single log
 * line when the runtime is missing. This is the one function services/agent
 * calls (see buildSdkEnv).
 *
 * The shim dir is *appended* to PATH, never prepended. It lives in userData, so
 * it is writable without privilege; at the head of PATH it would let anything
 * dropped there shadow `node` / `git` / `sh` for every agent subprocess and all
 * their descendants. Appended, only a name that exists nowhere else resolves
 * there — which is exactly `halo-node` and nothing more.
 *
 * NODE_PATH is deliberately not exported: the shim injects it for its own
 * process (see renderShimSh/renderShimCmd), and skills only reach the bundled
 * libraries through the shim. Exporting it here would instead put ~100 bundled
 * top-level packages on the module-resolution fallback path of every command the
 * agent runs, so a user project with an undeclared dependency would resolve it
 * from our bundle and pass locally while failing in CI.
 */
export function applyOfficeRuntimeEnv(env: Record<string, string | number | undefined>): void {
  const shimDir = ensureOfficeRuntimeShim()
  if (!shimDir) return

  const currentPath = typeof env.PATH === 'string' ? env.PATH : undefined
  env.PATH = currentPath ? `${currentPath}${delimiter}${shimDir}` : shimDir

  const fontsDir = getOfficeFontsDir()
  if (fontsDir) env.HALO_OFFICE_FONTS_DIR = fontsDir
}

/**
 * Startup self-check (Tier-3 idle task): run the shim end to end and require a
 * bundled library through it. Logs the outcome; never throws — a failing
 * runtime degrades office skills, nothing else.
 */
export async function verifyOfficeRuntime(): Promise<void> {
  const shimDir = ensureOfficeRuntimeShim()
  if (!shimDir) return

  const isWin = process.platform === 'win32'
  const shim = join(shimDir, isWin ? 'halo-node.cmd' : 'halo-node')
  const checkScript = join(shimDir, 'self-check.cjs')
  // cmd shims need a shell; with shell:true Node does not escape, so quote
  // both paths explicitly (userData paths routinely contain spaces).
  const [file, args] = isWin
    ? [`"${shim}"`, [`"${checkScript}"`]]
    : [shim, [checkScript]]
  await new Promise<void>((resolvePromise) => {
    execFile(
      file,
      args,
      { timeout: 20000, shell: isWin, windowsHide: true },
      (err, stdout, stderr) => {
        if (err || !String(stdout).includes('office-runtime-ok')) {
          console.error(
            '[OfficeRuntime] Self-check failed; office skills will degrade.',
            'error:', err?.message ?? 'unexpected output',
            'stdout:', String(stdout).slice(0, 500),
            'stderr:', String(stderr).slice(0, 500)
          )
        } else {
          console.log(`[OfficeRuntime] Self-check OK (shim: ${shim})`)
        }
        resolvePromise()
      }
    )
  })
}
